// <auto-generated />
using System;
using DataBaseManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataBaseManager.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250527152506_CreateAllTables")]
    partial class CreateAllTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataBaseManager.Models.Fundamentals", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("balance_sheet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cash_flow")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("earnings")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("provider_id")
                        .HasColumnType("int");

                    b.Property<int?>("stock_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("provider_id");

                    b.HasIndex("stock_id");

                    b.ToTable("fundamentals");
                });

            modelBuilder.Entity("DataBaseManager.Models.Indicators", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("macd")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("provider_id")
                        .HasColumnType("int");

                    b.Property<decimal>("rsi")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("sma")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("stock_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("provider_id");

                    b.HasIndex("stock_id");

                    b.ToTable("indicators");
                });

            modelBuilder.Entity("DataBaseManager.Models.Industries", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("industries");
                });

            modelBuilder.Entity("DataBaseManager.Models.News", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<string>("headline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("sentiment")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<string>("source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("stock_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.HasIndex("stock_id");

                    b.ToTable("news");
                });

            modelBuilder.Entity("DataBaseManager.Models.Price", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<decimal>("close")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<DateTime>("date")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("high")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("low")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<decimal>("open")
                        .HasPrecision(18, 4)
                        .HasColumnType("decimal(18,4)");

                    b.Property<int?>("provider_id")
                        .HasColumnType("int");

                    b.Property<int?>("stock_id")
                        .HasColumnType("int");

                    b.Property<long>("volume")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.HasIndex("provider_id");

                    b.HasIndex("stock_id");

                    b.ToTable("prices");
                });

            modelBuilder.Entity("DataBaseManager.Models.Provider", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("api_url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("auth_type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("providers");
                });

            modelBuilder.Entity("DataBaseManager.Models.Sector", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("sectors");
                });

            modelBuilder.Entity("DataBaseManager.Models.Stock", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int?>("industry_id")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("sector_id")
                        .HasColumnType("int");

                    b.Property<string>("symbol")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("industry_id");

                    b.HasIndex("sector_id");

                    b.ToTable("stocks");
                });

            modelBuilder.Entity("DataBaseManager.Models.Fundamentals", b =>
                {
                    b.HasOne("DataBaseManager.Models.Provider", null)
                        .WithMany("fundamentals")
                        .HasForeignKey("provider_id");

                    b.HasOne("DataBaseManager.Models.Stock", null)
                        .WithMany("fundamentals")
                        .HasForeignKey("stock_id");
                });

            modelBuilder.Entity("DataBaseManager.Models.Indicators", b =>
                {
                    b.HasOne("DataBaseManager.Models.Provider", null)
                        .WithMany("indicators")
                        .HasForeignKey("provider_id");

                    b.HasOne("DataBaseManager.Models.Stock", null)
                        .WithMany("indicators")
                        .HasForeignKey("stock_id");
                });

            modelBuilder.Entity("DataBaseManager.Models.News", b =>
                {
                    b.HasOne("DataBaseManager.Models.Stock", null)
                        .WithMany("news")
                        .HasForeignKey("stock_id");
                });

            modelBuilder.Entity("DataBaseManager.Models.Price", b =>
                {
                    b.HasOne("DataBaseManager.Models.Provider", null)
                        .WithMany("prices")
                        .HasForeignKey("provider_id");

                    b.HasOne("DataBaseManager.Models.Stock", null)
                        .WithMany("prices")
                        .HasForeignKey("stock_id");
                });

            modelBuilder.Entity("DataBaseManager.Models.Stock", b =>
                {
                    b.HasOne("DataBaseManager.Models.Industries", null)
                        .WithMany("stocks")
                        .HasForeignKey("industry_id");

                    b.HasOne("DataBaseManager.Models.Sector", null)
                        .WithMany("stocks")
                        .HasForeignKey("sector_id");
                });

            modelBuilder.Entity("DataBaseManager.Models.Industries", b =>
                {
                    b.Navigation("stocks");
                });

            modelBuilder.Entity("DataBaseManager.Models.Provider", b =>
                {
                    b.Navigation("fundamentals");

                    b.Navigation("indicators");

                    b.Navigation("prices");
                });

            modelBuilder.Entity("DataBaseManager.Models.Sector", b =>
                {
                    b.Navigation("stocks");
                });

            modelBuilder.Entity("DataBaseManager.Models.Stock", b =>
                {
                    b.Navigation("fundamentals");

                    b.Navigation("indicators");

                    b.Navigation("news");

                    b.Navigation("prices");
                });
#pragma warning restore 612, 618
        }
    }
}
