#
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - Predictions/**
    - azure-pipelines-template.yml

extends:
  template: ../azure-pipelines-template.yml
  parameters:
    servicePath: 'Predictions'
    imageName: 'ac-capp-predictions'
    containerAppName: 'ac-capp-predictions'