#
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - DataBaseManager/**
    - azure-pipelines-template.yml

extends:
  template: ../azure-pipelines-template.yml
  parameters:
    servicePath: 'DataBaseManager'
    imageName: 'ac-capp-database-manager'
    containerAppName: 'ac-capp-database-manager'